import { AuthProvider } from './provider';
import '../app/globals.css';
import Navbar from "@/app/components/Navbar/Navbar";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <div className="layout-container">
            <Navbar />
            <main className="main-content">
              {children}
              <ToastContainer />
            </main>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}

